### ISSUE TITLE
[improvement] add some editable table to add the points

### ISSUE THREAD

**Issue by ouinouin** [Onixarts/node-red-contrib-visualmapper#10]
hi, 
your plugin for nodered is awesome, just for values that needs precision it can be difficult to input the points with a mouse, it would be nice to be able to enter the points in a table or let the node take its parameters from  an array

**Comment by Onixarts** [comment]
Thanks. You're right. Just few days ago I've think about editing points in more precise way.

**Comment by ouinouin** [comment]
nice, hope to see that, the typical use case in automation is temperature offseting and compensation, i ll show you the use case, i plan to use your node to validate some test on a big furnace 😁

**Comment by Onixarts** [comment]
In any case... I think You should have an AZ-5 switch, IYKWIM ;)
