### ISSUE TITLE
Overzealous rounding

### ISSUE THREAD

**Issue by holgerpieta** [Onixarts/node-red-contrib-visualmapper#12]
I'm using a mapper set to round to 1, because the ACs controlled by the mapper only take full numbers for temperature.
It works fine for the output, but it feels to me that the UI applies that rounding setting at too many places:
- The tool tip next to the mouse pointer rounds both input and output to full numbers. While I might accept that for the output (though it makes precise placement of the key frames much harder), it doesn't make any sense for the input. Just because I want to round the outputs to full numbers doesn't mean that the inputs are also only full numbers. In my case they are not: They are outdoor temperature measurements precisely to 0.1 deg. And in other applications they may be a totally different physical value at a totally different scale.
- The input box after double clicking a key frame also rounds both input and output to full numbers. I can enter any number of digits I want and the key frame is placed precisely at the intended place (i.e. not rounded), but when I then close and reopen the box, the numbers are rounded to full number, which is just wrong, because that's not where the key frame actually is.

I think it would make sense to go back to the old behavior of rounding only the outputs and leave the UI alone. Or maybe round the UI to at least one, maybe two digits more than the output, at least for the output.
If you want to round the input, I think a separate configuration for the input rounding would be a good idea.

**Comment by Onixarts** [comment]
You're right. I made this rounding so it looks more clearly in the editor, but it can mess up keyframes when the precision is important.

**Comment by Onixarts** [comment]
I will add a checkbox option **Display rounded input** that will disable input rounding.

**Comment by holgerpieta** [comment]
Thanks, I'll try it when the new version makes it to the palette.
